import "./globals.css";
import { Inter as FontSans } from "next/font/google";
import { cn } from "@/lib/utils";
import { Toaster } from "@/components/ui/sonner";
import { ProgressBar } from "@/components";
import "@/middleware";
import dynamic from "next/dynamic";

const ThemeProvider = dynamic(() => import("@/components/theme-provider"), { ssr: false });

export const metadata = {
  title: "Next-admin",
  description: "Generated by Next.js",
};

const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
});

export default function RootLayout({ children }) {
  return (
    <html lang='en'>
      <body className={cn("min-h-screen bg-background font-sans antialiased", fontSans.variable)}>
        <ThemeProvider attribute='class' defaultTheme='light' enableSystem>
          <Toaster richColors position='top-center' />
          <ProgressBar />
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
